# The URL the site will be built for
base_url = "https://blog.dolczyk.rocks"
title = "dolczyk_rocks::blog"
description = ""

default_language = "en"

output_dir = "public"
preserve_dotfiles_in_output = false

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
generate_sitemap = true
generate_robots_txt = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

# Social links
[extra.socials]
portfolio = "https://dolczyk.rocks"
github = "https://github.com/dolczykk"
x = "https://x.com/MRmlik12"
linkedin = "https://www.linkedin.com/in/daniel-olczyk/"
email = "mailto:contact@dolczyk.rocks"
